<<<<<<< HEAD
=======
<<<<<<< HEAD
dependencies:
  override:
    - eval "$(curl -sL https://apt.vapor.sh)"
    - sudo apt-get install swift-beta
    - sudo chmod -R a+rx /usr/
test:
  override:
    - swift build
    - swift build -c release
    - swift test
=======
>>>>>>> 0122cd6473afa218f4b9729735e755da3a423ef8
version: 2

jobs:
  macos:
    macos:
      xcode: "9.0"
    steps:
<<<<<<< HEAD
=======
      - run: brew install vapor/tap/vapor
>>>>>>> 0122cd6473afa218f4b9729735e755da3a423ef8
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: swift:4.0
    steps:
<<<<<<< HEAD
      - run: apt-get install -yq libssl-dev
=======
      - run: apt-get install -y libssl-dev
      - checkout
      - run: swift build
      - run: swift test

  # 3.1 backward compat checks

  linux-3:
    docker:
      - image: swift:3.1
    steps:
      - run: apt-get install -y libssl-dev
>>>>>>> 0122cd6473afa218f4b9729735e755da3a423ef8
      - checkout
      - run: swift build
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
<<<<<<< HEAD
      - macos
      - linux
=======
      - linux
      - linux-3
      - macos
>>>>>>> master
>>>>>>> 0122cd6473afa218f4b9729735e755da3a423ef8
